const MAX_COUNT_PHOTOS = 25;
const MAX_COUNT_HASHTAGS = 5;
const MAX_LENGTH_HASHTAGS = 20;
const ALERT_SHOW_TIME = 4000;
const TIME_OUT_DELAY = 500;
const MAX_COMMENTS_TO_SHOW = 5;
const RANDOM_QUANTITY = 10;
const MAX_STRING_LENGTH = 140;
const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png', 'heic'];
const HASHTAGS_QUANTITY = 5;
const TAG_REGEX = /^#[A-Za-zА-Яа-яЕё0-9]{1,19}$/i;
const MAX_TAGS_NUMBER = 5;
const SCALE_STEP = 25;
const MIN_SCALE_VALUE = 25;
const MAX_SCALE_VALUE = 100;

export { MAX_COUNT_PHOTOS, MAX_COUNT_HASHTAGS, MAX_LENGTH_HASHTAGS, ALERT_SHOW_TIME, TIME_OUT_DELAY, MAX_COMMENTS_TO_SHOW, RANDOM_QUANTITY, MAX_STRING_LENGTH, FILE_TYPES, HASHTAGS_QUANTITY, TAG_REGEX, MAX_TAGS_NUMBER, SCALE_STEP, MAX_SCALE_VALUE, MIN_SCALE_VALUE };
