const MAX_COUNT_PHOTOS = 25;
const MAX_COUNT_HASHTAGS = 5;
const MAX_LENGTH_HASHTAGS = 20;
const ALERT_SHOW_TIME = 4000;
const TIME_OUT_DELAY = 500;
const MAX_COMMENTS_TO_SHOW = 5;
const RANDOM_QUANTITY = 10;

export { MAX_COUNT_PHOTOS, MAX_COUNT_HASHTAGS, MAX_LENGTH_HASHTAGS, ALERT_SHOW_TIME, TIME_OUT_DELAY, MAX_COMMENTS_TO_SHOW, RANDOM_QUANTITY };
